<a href="https://colab.research.google.com/github/MiguelITSON/prueba/blob/main/Preparaci%C3%B3n_R_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A <- 6

A[A<=6]

[1] 6

In [ ]:
diag(2,nrow = 4,ncol = 4)


[,1] [,2] [,3] [,4]
[1,] 2    0    0    0   
[2,] 0    2    0    0   
[3,] 0    0    2    0   
[4,] 0    0    0    2

In [ ]:
Evaluaciones <- matrix(c(7,6.5,9.2,8.6,8,
7.5,9.4,7.3,7,7,
7.6,9.2,8,8,7.5,
5,6.5,6.5,7,9,
6,6,7.8,8.9,7.3,
7.8,9.6,7.7,8,6.5,
6.3,6.4,8.2,9,7.2,
7.9,9.7,7.5,8,6,
6,6,6.5,5.5,8.7,
6.8,7.2,8.7,9,7),nrow = 10,ncol = 5, byrow = T, dimnames = list(c('Lucia', 'Pedro', 'Ines', 'Luis', 'Andres', 'Ana', 'Carlos', 'Jose', 'Sonia', 'Maria'),
c('Matematicas', 'Ciencias', 'Español', 'Historia', 'Fisica')))

Evaluaciones


Matematicas Ciencias Español Historia Fisica
Lucia  7.0         6.5      9.2     8.6      8.0   
Pedro  7.5         9.4      7.3     7.0      7.0   
Ines   7.6         9.2      8.0     8.0      7.5   
Luis   5.0         6.5      6.5     7.0      9.0   
Andres 6.0         6.0      7.8     8.9      7.3   
Ana    7.8         9.6      7.7     8.0      6.5   
Carlos 6.3         6.4      8.2     9.0      7.2   
Jose   7.9         9.7      7.5     8.0      6.0   
Sonia  6.0         6.0      6.5     5.5      8.7   
Maria  6.8         7.2      8.7     9.0      7.0

In [ ]:
t(rep(1,5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1

In [ ]:
vector_columna1 <- matrix(rep(1,5),nrow = 5, ncol = 1, byrow = T)
#vector_columna1

Media_alumno <- t(1/5*Evaluaciones%*%vector_columna1)
Media_alumno


Lucia Pedro Ines Luis Andres Ana  Carlos Jose Sonia Maria
[1,] 7.86  7.64  8.06 6.8  7.2    7.92 7.42   7.82 6.54  7.74

In [ ]:
vector_columna2 <- matrix(rep(1,10),nrow = 10, ncol = 1, byrow = T)
vector_columna2

media_materias <- t(1/10*t(Evaluaciones)%*%(vector_columna2))
media_materias

[,1]
 [1,] 1   
 [2,] 1   
 [3,] 1   
 [4,] 1   
 [5,] 1   
 [6,] 1   
 [7,] 1   
 [8,] 1   
 [9,] 1   
[10,] 1

Matematicas Ciencias Español Historia Fisica
[1,] 6.79        7.65     7.74    7.9      7.42

In [ ]:
t(Evaluaciones)

Lucia Pedro Ines Luis Andres Ana Carlos Jose Sonia Maria
Matematicas 7.0   7.5   7.6  5.0  6.0    7.8 6.3    7.9  6.0   6.8  
Ciencias    6.5   9.4   9.2  6.5  6.0    9.6 6.4    9.7  6.0   7.2  
Español     9.2   7.3   8.0  6.5  7.8    7.7 8.2    7.5  6.5   8.7  
Historia    8.6   7.0   8.0  7.0  8.9    8.0 9.0    8.0  5.5   9.0  
Fisica      8.0   7.0   7.5  9.0  7.3    6.5 7.2    6.0  8.7   7.0

In [ ]:
identidad1 <- diag(1,nrow = 10, ncol = 10)
identidad1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 1    0    0    0    0    0    0    0    0    0    
 [2,] 0    1    0    0    0    0    0    0    0    0    
 [3,] 0    0    1    0    0    0    0    0    0    0    
 [4,] 0    0    0    1    0    0    0    0    0    0    
 [5,] 0    0    0    0    1    0    0    0    0    0    
 [6,] 0    0    0    0    0    1    0    0    0    0    
 [7,] 0    0    0    0    0    0    1    0    0    0    
 [8,] 0    0    0    0    0    0    0    1    0    0    
 [9,] 0    0    0    0    0    0    0    0    1    0    
[10,] 0    0    0    0    0    0    0    0    0    1

In [ ]:
unos <- matrix(rep(1,10),nrow = 10, ncol = 1, byrow = T)
unos

[,1]
 [1,] 1   
 [2,] 1   
 [3,] 1   
 [4,] 1   
 [5,] 1   
 [6,] 1   
 [7,] 1   
 [8,] 1   
 [9,] 1   
[10,] 1

In [ ]:
S_materias <- 1/9*t(Evaluaciones)%*%(identidad1 - 1/10*unos %*% t(unos))%*% Evaluaciones
S_materias

Matematicas Ciencias    Español     Historia    Fisica    
Matematicas  0.9054444   1.30833333  0.31488889  0.22111111 -0.6953333
Ciencias     1.3083333   2.59166667 -0.02777778 -0.03888889 -1.0277778
Español      0.3148889  -0.02777778  0.74044444  0.79222222 -0.2920000
Historia     0.2211111  -0.03888889  0.79222222  1.25777778 -0.5288889
Fisica      -0.6953333  -1.02777778 -0.29200000 -0.52888889  0.8617778

In [ ]:
identidad2 <- diag(1,nrow = 5, ncol = 5)

In [ ]:
unos2 <- matrix(rep(1,5), nrow = 5, ncol = 1, byrow = T)
unos2

[,1]
[1,] 1   
[2,] 1   
[3,] 1   
[4,] 1   
[5,] 1

In [ ]:
S_alumnos <- 1/4* Evaluaciones %*% (identidad2 - 1/5 * unos2 %*% t(unos2)) %*% t(Evaluaciones)
S_alumnos

Lucia   Pedro   Ines    Luis    Andres  Ana     Carlos  Jose    Sonia  
Lucia   1.2380 -0.8230 -0.3395  0.5025  1.1850 -0.6540  1.1335 -0.7940  0.1695
Pedro  -0.8230  1.0130  0.6220 -0.4275 -0.8250  0.9765 -0.6935  1.1140 -0.3945
Ines   -0.3395  0.6220  0.4580 -0.1850 -0.2525  0.6935 -0.1665  0.7835 -0.3780
Luis    0.5025 -0.4275 -0.1850  2.0750  0.7250 -0.8325  0.4800 -1.1450  1.4225
Andres  1.1850 -0.8250 -0.2525  0.7250  1.5350 -0.5025  1.4250 -0.6050 -0.0700
Ana    -0.6540  0.9765  0.6935 -0.8325 -0.5025  1.2270 -0.3280  1.4545 -0.9960
Carlos  1.1335 -0.6935 -0.1665  0.4800  1.4250 -0.3280  1.3620 -0.3930 -0.2485
Jose   -0.7940  1.1140  0.7835 -1.1450 -0.6050  1.4545 -0.3930  1.7470 -1.2910
Sonia   0.1695 -0.3945 -0.3780  1.4225 -0.0700 -0.9960 -0.2485 -1.2910  1.5830
Maria   0.9145 -0.3695  0.0245  0.0475  1.1050  0.0365  1.1265  0.0440 -0.5370
       Maria  
Lucia   0.9145
Pedro  -0.3695
Ines    0.0245
Luis    0.0475
Andres  1.1050
Ana     0.0365
Carlos  1.1265
Jose    0.0440
Sonia  -0.5370
Maria   1.0580

In [ ]:
sd_materias <- sqrt(diag(S_materias))
sd_materias

sd_alumno <- sqrt(diag(S_alumnos))
sd_alumno

Matematicas    Ciencias     Español    Historia      Fisica 
  0.9515484   1.6098654   0.8604908   1.1215069   0.9283199

Lucia    Pedro     Ines     Luis   Andres      Ana   Carlos     Jose 
1.112654 1.006479 0.676757 1.440486 1.238951 1.107700 1.167048 1.321741 
   Sonia    Maria 
1.258173 1.028591

In [ ]:
traza_materias <- sum(diag(S_materias))
traza_materias

traza_alumno <- sum(diag(S_alumnos))
traza_alumno

[1] 6.357111

[1] 13.296

In [ ]:
det(S_alumnos)
det(S_materias)

[1] -8.067358e-92

[1] 0.003353316

In [ ]:
media_materias


Matematicas Ciencias Español Historia Fisica
[1,] 6.79        7.65     7.74    7.9      7.42

In [ ]:
dim(Evaluaciones)
unos

[1] 10  5

[,1]
 [1,] 1   
 [2,] 1   
 [3,] 1   
 [4,] 1   
 [5,] 1   
 [6,] 1   
 [7,] 1   
 [8,] 1   
 [9,] 1   
[10,] 1

In [ ]:
1/10*t(unos)%*%Evaluaciones

Matematicas Ciencias Español Historia Fisica
[1,] 6.79        7.65     7.74    7.9      7.42

In [ ]:
unos %*% media_materias

Matematicas Ciencias Español Historia Fisica
 [1,] 6.79        7.65     7.74    7.9      7.42  
 [2,] 6.79        7.65     7.74    7.9      7.42  
 [3,] 6.79        7.65     7.74    7.9      7.42  
 [4,] 6.79        7.65     7.74    7.9      7.42  
 [5,] 6.79        7.65     7.74    7.9      7.42  
 [6,] 6.79        7.65     7.74    7.9      7.42  
 [7,] 6.79        7.65     7.74    7.9      7.42  
 [8,] 6.79        7.65     7.74    7.9      7.42  
 [9,] 6.79        7.65     7.74    7.9      7.42  
[10,] 6.79        7.65     7.74    7.9      7.42

In [ ]:
evaluacion_centrada <- Evaluaciones - unos %*% media_materias

evaluacion_centrada

Matematicas Ciencias Español Historia Fisica
Lucia   0.21       -1.15     1.46    0.7      0.58 
Pedro   0.71        1.75    -0.44   -0.9     -0.42 
Ines    0.81        1.55     0.26    0.1      0.08 
Luis   -1.79       -1.15    -1.24   -0.9      1.58 
Andres -0.79       -1.65     0.06    1.0     -0.12 
Ana     1.01        1.95    -0.04    0.1     -0.92 
Carlos -0.49       -1.25     0.46    1.1     -0.22 
Jose    1.11        2.05    -0.24    0.1     -1.42 
Sonia  -0.79       -1.65    -1.24   -2.4      1.28 
Maria   0.01       -0.45     0.96    1.1     -0.42

In [ ]:
diag(S_materias)

Matematicas    Ciencias     Español    Historia      Fisica 
  0.9054444   2.5916667   0.7404444   1.2577778   0.8617778

In [ ]:
invsd_matriz <- sqrt(diag(1/diag(S_materias),nrow = 5, ncol = 5))
invsd_matriz


[,1]     [,2]      [,3]     [,4]      [,5]    
[1,] 1.050919 0.0000000 0.000000 0.0000000 0.000000
[2,] 0.000000 0.6211699 0.000000 0.0000000 0.000000
[3,] 0.000000 0.0000000 1.162127 0.0000000 0.000000
[4,] 0.000000 0.0000000 0.000000 0.8916574 0.000000
[5,] 0.000000 0.0000000 0.000000 0.0000000 1.077215

In [ ]:
Diagonal <- invsd_matriz
Diagonal

S <- diag(diag(S_materias),nrow = 5, ncol = 5)
S

[,1]     [,2]      [,3]     [,4]      [,5]    
[1,] 1.050919 0.0000000 0.000000 0.0000000 0.000000
[2,] 0.000000 0.6211699 0.000000 0.0000000 0.000000
[3,] 0.000000 0.0000000 1.162127 0.0000000 0.000000
[4,] 0.000000 0.0000000 0.000000 0.8916574 0.000000
[5,] 0.000000 0.0000000 0.000000 0.0000000 1.077215

[,1]      [,2]     [,3]      [,4]     [,5]     
[1,] 0.9054444 0.000000 0.0000000 0.000000 0.0000000
[2,] 0.0000000 2.591667 0.0000000 0.000000 0.0000000
[3,] 0.0000000 0.000000 0.7404444 0.000000 0.0000000
[4,] 0.0000000 0.000000 0.0000000 1.257778 0.0000000
[5,] 0.0000000 0.000000 0.0000000 0.000000 0.8617778

In [ ]:
S_materias

Matematicas Ciencias    Español     Historia    Fisica    
Matematicas  0.9054444   1.30833333  0.31488889  0.22111111 -0.6953333
Ciencias     1.3083333   2.59166667 -0.02777778 -0.03888889 -1.0277778
Español      0.3148889  -0.02777778  0.74044444  0.79222222 -0.2920000
Historia     0.2211111  -0.03888889  0.79222222  1.25777778 -0.5288889
Fisica      -0.6953333  -1.02777778 -0.29200000 -0.52888889  0.8617778

In [ ]:
#Coeficiente de correlación
R <- Diagonal%*%S_materias%*%Diagonal

#R

rownames(R) <- c('Matematicas','Ciencias','Español','Historia','Fisica')
colnames(R) <- c('Matematicas','Ciencias','Español','Historia','Fisica')
R

Matematicas Ciencias    Español     Historia    Fisica    
Matematicas  1.0000000   0.85407878  0.38457424  0.20719425 -0.7871627
Ciencias     0.8540788   1.00000000 -0.02005218 -0.02153942 -0.6877206
Español      0.3845742  -0.02005218  1.00000000  0.82091619 -0.3655434
Historia     0.2071943  -0.02153942  0.82091619  1.00000000 -0.5080013
Fisica      -0.7871627  -0.68772056 -0.36554342 -0.50800132  1.0000000

In [ ]:
170+1716.98+200+22.41+199.9+800+92.6+520+231.65+39.9+916.58+491.58+271

[1] 5672.6

In [ ]:
6490/24

[1] 270.4167